name: ci-cd pipeline for frontend

on:
 push:
    branches: [main]
 pull_request:
    branches: [main]

jobs:
#validate code and run tests
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: |
          cd frontend && npm install
      - name: install Eslint
        run: |
            cd frontend && npm install eslint --save-dev
      - name: lint with eslint
        run: |
          cd frontend && npx eslint .
      - name: Run tests
        run: |
            npm test

  build-and-push:
    runs-on: ubuntu-latest
    #uses permission to read and write for OIDC token to authenticate with aws
    permissions:
      contents: read    
      id-token: write
    needs: validate-code
    steps:
      - uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: loging in aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
            aws-region: ${{ secrets.AWS_REGION }}     
    
      - name: build docker image
        run: | 
            docker build -t my-frontend-app:${ github.sha } ./frontend
      - name: scan vulnerabilities with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-frontend-app:${ github.sha }
          format: 'table'
          exit-code: '1'
          severity: CRITICAL,HIGH
          trivyignorefile: .trivyignore

      - name: push docker image to ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: push docker image
        run: |
            docker tag my-frontend-app:${ github.sha } ${{ secrets.AWS_ECR_BACKEND_URL }}:my-frontend-app-${ github.sha }
            docker push ${{ secrets.AWS_ECR_BACKEND_URL }}:my-frontend-app-${ github.sha }

        